name: fire-monitoring-tutorial
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - aiohttp
  - jupyter
  - mbutil
  - ndpyramid
  - pre-commit
  - pygmt
  - requests
  - rioxarray
  - tippecanoe
  - pip:
      - git+https://github.com/carbonplan/forest-offsets-fires.git
      - carbonplan-data
